import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  mainSidebar: [
    {
      type: 'category',
      label: 'Phonology',
      items: [{type: 'autogenerated', dirName: 'phonology'}],
    },
    {
      type: 'category',
      label: 'Morphology',
      items: [{type: 'autogenerated', dirName: 'morphology'}],
    },
    {
      type: 'category',
      label: 'Syntax',
      items: [{type: 'autogenerated', dirName: 'syntax'}],
    },
    {
      type: 'category',
      label: 'Vocabulary',
      items: [{type: 'autogenerated', dirName: 'vocabulary'}],
    },
  ],
};

export default sidebars;
